### ISSUE TITLE
Modules load problem in workers

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#1098]
Some modules, for example `argon2` can't be loaded in worker threads.

Try `load.js` with the following code:
```js
'use strict';

const { Worker } = require('worker_threads');

const argon2 = require('argon2');
console.dir({ argon2 });

new Worker('./thread.js');
```
and `thread.js` with the following code:
```js
'use strict';

const argon2 = require('argon2');

console.dir({ argon2 });
```
we will get exception:
```
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:775:18)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (.../node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (.../node_modules/argon2/argon2.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
```
We need to find solution to use worker thread in impress. @nechaido you can assign this task to developers.

**Comment by tshemsedinov** [comment]
After resolving this problem we can use solution here: https://github.com/metarhia/impress/pull/1099

**Comment by lundibundi** [comment]
worker_threads doesn't support native addons as of 11.9.0 [
"Native addons are not supported yet."](https://nodejs.org/api/worker_threads.html#worker_threads_class_worker) therefore it won't be possible to `require('argon2')` in them as npm `argon2` module is just bindings to the C argon library.

**Comment by tshemsedinov** [comment]
It works in 11.9.0 if you require from a single worker, but fails if you require from master process and 1 worker or from more then 1 workers. We need at least: mdsf, websocket, argon2

**Comment by lundibundi** [comment]
Refs: https://github.com/nodejs/node/pull/26175
