### ISSUE TITLE
Impress crash on incorrect config files

### ISSUE THREAD

**Issue by lundibundi** [metarhia/impress#1142]
If you make an error in 'config' files of impress (e.g. config/log.test.js) it will crash with 

```cmd
Testing Impress Application Server...
TypeError: application.logException is not a function
    at prepareScript (/lib/scripts.js:62:17)
    at api.fs.readFile (/lib/scripts.js:83:17)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
/home/lundibundi/dev/node/metarhia/impress/lib/core.js:593
    impress.log.system('Stopped server');
                ^

TypeError: Cannot read property 'system' of undefined
    at EventEmitter.impress.shutdown (/home/lundibundi/dev/node/metarhia/impress/lib/core.js:593:17)
    at EventEmitter.impress.fatalError.err [as fatalError] (/home/lundibundi/dev/node/metarhia/impress/lib/core.js:74:13)
    at process.on.err (/home/lundibundi/dev/node/metarhia/impress/lib/core.js:114:11)
    at process.emit (events.js:202:15)
    at process.EventEmitter.emit (domain.js:446:20)
    at process._fatalException (internal/process/execution.js:127:25)
```

This is partially fixed by https://github.com/metarhia/impress/pull/1140 but not fully.

Reproduce:

Add semicolon at the end of `config/log.test.js` and run `npm test`.

**Comment by tshemsedinov** [comment]
In future we need logger that can start logging to console before configuration loaded.
