### ISSUE TITLE
Issue with application startup after updating node version to 20.12.0

### ISSUE THREAD

**Issue by sarnakov** [metarhia/impress#1964]
### Impress and Node.js versions

20.12.0

### Platform

Darwin Oleksiis-MacBook-Air.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64

### Describe the bug

The project works perfectly on 20.11.0 node version but throws following error on 20.12.0

/node_modules/impress/lib/deps.js:95
node.timers.promises = require('node:timers/promises');
                     ^

TypeError: Cannot set property promises of #<Object> which has only a getter
    at Object.<anonymous> (/[redacted]/node_modules/impress/lib/deps.js:95:22)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/[redacted]/node_modules/impress/lib/planner.js:3:32)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/[redacted]/node_modules/impress/impress.js:13:21)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)

**Comment by tshemsedinov** [comment]
Please check impress version

**Comment by tshemsedinov** [comment]
Fixed two months ago: https://github.com/metarhia/impress/commit/a2a7ad0407484baf911208b3ab48295c4b631a0d
