### ISSUE TITLE
Impress 0.3 installed with a deployment script does not start on a server

### ISSUE THREAD

**Issue by aqrln** [metarhia/Impress#557]
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/ias/schemas/config.impress.definition.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.api.definition.require (/ias/node_modules/impress/lib/api.definition.js:15:27)
    at Object.<anonymous> (/ias/node_modules/impress/lib/impress.js:34:49)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at fs.exists (/ias/server.js:7:8)
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```

CentOS 7, Node.js 6.3, Impress 0.3.3

**Comment by tshemsedinov** [comment]
Unpublished 0.3.2 and 0.3.3
