### ISSUE TITLE
Use once instead of deprecated cb (metasync)

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/impress#795]
```
Impress Application Server starting, reading configuration
  JSTP listen on 127.0.0.1:2500 by Master(3830/S1N0) Master Server
  JSTP listen on 127.0.0.1:3000 by Worker(3848/S1N2)
  JSTP/WS listen on 127.0.0.1:5000 by Worker(3850/S1N3)
{ Warning: use once instead of deprecated as cb
    at Object.wrap [as cb] (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/utilities.js:30:19)
    at MemoryProvider.StorageProvider.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/lib/provider.js:16:21)
    at MemoryProvider.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/lib/provider.memory.js:16:34)
    at GlobalStorage.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/gs.js:57:15)
    at EventEmitter.application.on (/home/travis/build/metarhia/impress/lib/api.db.gs.js:26:14)
    at EventEmitter.emit (events.js:164:20)
    at api.metasync.each (/home/travis/build/metarhia/impress/lib/api.db.js:64:17)
    at wrap (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/callbacks.js:46:5)
    at next (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:156:24)
    at driver.open (/home/travis/build/metarhia/impress/lib/api.db.js:102:7)
    at wrap (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/callbacks.js:46:5)
    at next (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:156:24)
    at con.collection (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:60:13)
    at Db.collection (/home/travis/build/metarhia/impress/node_modules/mongodb/lib/db.js:463:20)
    at api.metasync.each (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:57:13)
    at Function.each (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:161:5)
    at Object.database.loadCollections (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:56:20)
    at client.connect (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:31:18)
    at connectCallback (/home/travis/build/metarhia/impress/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /home/travis/build/metarhia/impress/node_modules/mongodb/lib/mongo_client.js:430:11
    at process._tickCallback (internal/process/next_tick.js:150:11) message: 'Warning: use once instead of deprecated as cb' }
{ Warning: use once instead of deprecated as cb
    at Object.wrap [as cb] (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/utilities.js:30:19)
    at MemoryProvider.StorageProvider.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/lib/provider.js:16:21)
    at MemoryProvider.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/lib/provider.memory.js:16:34)
    at GlobalStorage.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/gs.js:57:15)
    at EventEmitter.application.on (/home/travis/build/metarhia/impress/lib/api.db.gs.js:26:14)
    at EventEmitter.emit (events.js:164:20)
    at api.metasync.each (/home/travis/build/metarhia/impress/lib/api.db.js:64:17)
    at wrap (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/callbacks.js:46:5)
    at next (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:156:24)
    at driver.open (/home/travis/build/metarhia/impress/lib/api.db.js:102:7)
    at wrap (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/callbacks.js:46:5)
    at next (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:156:24)
    at con.collection (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:60:13)
    at Db.collection (/home/travis/build/metarhia/impress/node_modules/mongodb/lib/db.js:463:20)
    at api.metasync.each (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:57:13)
    at Function.each (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:161:5)
    at Object.database.loadCollections (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:56:20)
    at client.connect (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:31:18)
    at connectCallback (/home/travis/build/metarhia/impress/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /home/travis/build/metarhia/impress/node_modules/mongodb/lib/mongo_client.js:430:11
    at process._tickCallback (internal/process/next_tick.js:150:11) message: 'Warning: use once instead of deprecated as cb' }
  HTTP listen on 127.0.0.1:8080 by Worker(3843/S1N1)
{ Warning: use once instead of deprecated as cb
    at Object.wrap [as cb] (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/utilities.js:30:19)
    at MemoryProvider.StorageProvider.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/lib/provider.js:16:21)
    at MemoryProvider.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/lib/provider.memory.js:16:34)
    at GlobalStorage.open (/home/travis/build/metarhia/impress/node_modules/globalstorage/gs.js:57:15)
    at EventEmitter.application.on (/home/travis/build/metarhia/impress/lib/api.db.gs.js:26:14)
    at EventEmitter.emit (events.js:164:20)
    at api.metasync.each (/home/travis/build/metarhia/impress/lib/api.db.js:64:17)
    at wrap (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/callbacks.js:46:5)
    at next (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:156:24)
    at driver.open (/home/travis/build/metarhia/impress/lib/api.db.js:102:7)
    at wrap (/home/travis/build/metarhia/impress/node_modules/metarhia-common/lib/callbacks.js:46:5)
    at next (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:156:24)
    at con.collection (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:60:13)
    at Db.collection (/home/travis/build/metarhia/impress/node_modules/mongodb/lib/db.js:463:20)
    at api.metasync.each (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:57:13)
    at Function.each (/home/travis/build/metarhia/impress/node_modules/metasync/lib/array.js:161:5)
    at Object.database.loadCollections (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:56:20)
    at client.connect (/home/travis/build/metarhia/impress/lib/api.db.mongodb.js:31:18)
    at connectCallback (/home/travis/build/metarhia/impress/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /home/travis/build/metarhia/impress/node_modules/mongodb/lib/mongo_client.js:430:11
    at process._tickCallback (internal/process/next_tick.js:150:11) message: 'Warning: use once instead of deprecated as cb' }
```

**Comment by tshemsedinov** [comment]
Fixed in https://github.com/metarhia/impress/pull/799
