### ISSUE TITLE
Wrong error handling in impress.fatalError

### ISSUE THREAD

**Issue by ykolomiets** [metarhia/impress#827]
Hello, guys! We have a new bug and don't know what to do:
```
/home/app/node_modules/impress/lib/impress.js:100
    if (err.stack.includes(path)) return appName;
                 ^

TypeError: Cannot read property 'includes' of undefined
    at EventEmitter.impress.findApplicationByStack (/home/app/node_modules/impress/lib/impress.js:100:18)
    at EventEmitter.impress.fatalError (/home/app/node_modules/impress/lib/impress.js:108:27)
    at Timeout.api.timers.setInterval [as _onTimeout] (/home/app/node_modules/impress/lib/impress.js:164:15)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

Can you advise something? Thanks in advance

**Comment by ykolomiets** [comment]
@aqrln

**Comment by aqrln** [comment]
I don't think we can do much without a reproduction. Can you please provide a minimal example that shows the bug? My *assumption*, though, would be that you throw something that is not an instance of `Error` somewhere in your code.

**Comment by ykolomiets** [comment]
Thanks, we have no code with throw((
This is from impress.js:
```
impress.findApplicationByStack = (err) => {
  let appName, path;
  for (appName in impress.applications) {
    path = '/applications/' + appName;
    if (err.stack.includes(path)) return appName;
  }
};

impress.fatalError = (
  // Fatal error with process termination
  err // instance of Error or string
) => {
  const appName = impress.findApplicationByStack(err);

  //here a lot of code
}
```

So if impress.fatalError is called with string parameter it causes an error in impress.findApplicationByStack, isn't it?

And some examples of impress.fatalError`s calls:
```
163     if (mu.heapTotal > impress.memoryLimit) {
164       impress.fatalError(
165         'Memory limit exceeded: ' +
166         api.common.bytesToSize(mu.heapTotal) +
167         ', restarting'
168       );
169     }


//

238       if (err) {
239         impress.fatalError(impress.CANT_READ_DIR + impress.applicationsDir);
240         callback();
241       }

//

339         else impress.fatalError(ALREADY_STARTED);

//

580       const error = new Error(msg);
581       error.code = 'EBIND';
582       impress.fatalError(error);

```

Is it OK?

**Comment by tshemsedinov** [comment]
@ykolomiets try Version 0.5.2

**Comment by ykolomiets** [comment]
Thanks, the problem is solved
